ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      bundle install --without production &&
      yarn install &&
      rails db:migrate
    command: >
      rails server
github:
  prebuilds:
    pullRequestsFromForks: true
